include:
  - template: Composer.gitlab-ci.yml

stages:
  - test
  - build

publish:
  cache:
    - key: composer
      paths:
        - vendor/
  rules:
    - if: '$CI_COMMIT_BRANCH == "gitlab-testing"'

composer_test:
  cache:
  - key: composer-dev
    paths:
      - vendor/
  image: composer:1
  stage: test
  before_script:
    - composer install --ignore-platform-reqs
  script:
    - composer test
